from collections.abc import Sequence

from PySide6.QtCore import QAbstractTableModel, QModelIndex, Qt, QSortFilterProxyModel
from ct_pcd_gui.features.lesion_viewer.domain.models import LesionFileRecord


class LesionFileTableModel(QAbstractTableModel):
    COLUMNS = ("Name", "Folder", "Type", "Size")

    def clear(self) -> None: ...
    def replace(self, records: Sequence[LesionFileRecord]) -> None: ...
    def append_batch(self, records: Sequence[LesionFileRecord]) -> None: ...
    def record_at(self, row: int) -> LesionFileRecord | None: ...
    def rowCount(self, parent=QModelIndex()) -> int: ...
    def columnCount(self, parent=QModelIndex()) -> int: ...
    def data(self, index, role=Qt.ItemDataRole.DisplayRole): ...

    def headerData(self, section, orientation, role=Qt.ItemDataRole.DisplayRole): ...

    def sort(self, column, order=Qt.SortOrder.AscendingOrder): ...


class LesionFileFilterProxy(QSortFilterProxyModel):
    def filterAcceptsRow(self, source_row: int, source_parent) -> bool: ...


def _format_size(size_bytes: int) -> str:
    size = float(size_bytes)
    for unit in ("B", "KB", "MB", "GB", "TB"):
        if size < 1024.0 or unit == "TB":
            return f"{size:.0f} {unit}" if unit == "B" else f"{size:.1f} {unit}"
        size /= 1024.0
    return f"{size_bytes:,} B"
